language: node_js

node_js:
  - "0.10"

env:
  global:
    - secure: "Rm4C2xPbb3a1j9BfA29mwtbkRF3GF9pAXdr3F3Stu46/wJb2uToxstvqbP7Q1QkpXKmOB26GYHtlC5ANgjuakLNm59Ke1JLMO4Nfg7H4aPdLJb/8xnJYmZK7ACRUGpa/Q7vQZ+3loN2BmwIytX/bDkGuJ9ONjg6DdGL1egjPDS0="
    - GIT_REPO=jquery-pjax
    - GIT_COMMITTER_NAME=Travis-CI
    - GIT_COMMITTER_EMAIL=Travis-CI
    - GIT_AUTHOR_NAME=falsandtru
    - GIT_AUTHOR_EMAIL=falsandtru

  matrix:
    - jquery=1.4.2
      deploy=false
    - jquery=1.5.0
      deploy=false
    - jquery=1.6.0
      deploy=false
    - jquery=1.7.2
      deploy=true
    - jquery=1.11.1
      deploy=false
    - jquery=2.1.1
      deploy=false

script:
  - grunt travis

after_success:
  - if [ $TRAVIS_BRANCH != "master" ] || [ ! $GH_TOKEN ]; then exit 0; fi
  - if [ $deploy == "false" ]; then exit 0; fi
  - mkdir ../gh-pages
  - cp -rf ./gh-pages ../
  - cp -rf ./test ../gh-pages
  - cat package.json | json version
  - new_version=`cat package.json | json version | awk -F. '{printf("%d%05d%06d", ++$1, $2, $3)}'`
  - git reset --hard HEAD~
  - cat package.json | json version
  - cat package.json | json version | awk -F. '{printf("%d%05d%06d", ++$1, $2, $3)}'
  - old_version=`cat package.json | json version | awk -F. '{printf("%d%05d%06d", ++$1, $2, $3)}'`
  - git reset --hard ORIG_HEAD
  - if [ $new_version -lt $old_version ]; then exit 0; fi
  - git fetch origin gh-pages:gh-pages
  - git checkout --orphan gh-pages
  - git checkout -m gh-pages
  - ls -a | grep -vE "^.git$|^\.+$" | xargs rm -rf
  - cp -rf ../gh-pages/* ./
  - find | grep -vE "^./.git(/|$)"
  - sed -i 's|\(baseurl:\s\+\)|\1//falsandtru.github.io|' _config.yml
  - git add -A :/
  - git commit -m 'Deploy by Travis-CI'
  - git push https://${GH_TOKEN}@github.com/${GIT_AUTHOR_NAME}/${GIT_REPO}.git gh-pages:gh-pages 2>&1 | sed -e "s/:\/\/\w\+@/:\/\/[secure]@/g"

notifications:
  email:
    recipients:
      - secure: "YLOgVXRlFdYYN6uxjq0C3M+5V0oWqDL45M89Z4HaDkKdMXOGGgv67GKVpEGyXFrEHSWiqe+Ud2xe9O+N4LVxuRpOCoskQxG9qlSYe486xpHdDoK271FfhupN4JxJjKPJmnIsCV2lPmiTW9AS0+ZtELE1cDn8+mQQL19m2RyT4q4="
    on_success: change # default: change
    on_failure: always # default: always
