# Engine
encoding: UTF-8
markdown: kramdown
kramdown:
  input: GFM

## Plugin
gems:
  - jekyll-redirect-from

# Config
baseurl: /pjax-api
permalink: /:categories/:year/:month/:day/:title

# Param
basepath: /pjax-api/
title: PJAX
